config/routes.rb
Suppert::Application.routes.draw do

  devise_for :members

  resources :tickets, except: :index

  namespace :staff do
    resources :tickets, only: :show do
      collection do
        %w/unassigned open onhold closed/.each { |action| get action }
        post :search
      end
      put 'take_ownership', on: :member
      resources :replies
    end

    root to: 'tickets#unassigned'
  end

  root to: 'tickets#new'
end

app/models/department.rb
class Department < ActiveRecord::Base

  attr_accessible :name
  
  validates :name, presence: true
  
  def to_s
    self.name
  end

end

app/models/member.rb
class Member < ActiveRecord::Base

  devise :database_authenticatable, :registerable, :rememberable

  attr_accessible :username, :password, :password_confirmation, :remember_me

  validates :username, presence: true, uniqueness: { case_sensitive: false }

  def to_s
    self.username
  end
  
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  attr_accessible :response, :new_assignee_id, :new_status_id

  belongs_to :ticket
  belongs_to :author,       class_name: 'Member'
  belongs_to :new_assignee, class_name: 'Member'

  validates :response, presence: true

  after_commit  :update_ticket,     on: :create
  after_commit  :send_notification, on: :create

  def new_status
    Ticket::STATUS.invert[new_status_id]
  end

  def update_ticket
    ticket.status   = new_status   if new_status.present?
    ticket.assignee = new_assignee if new_assignee.present?
    ticket.save
  end

  def send_notification
    TicketNotifications.replied(self).deliver
  end
end

app/models/search.rb
class Search

  attr_accessor :query, :results

  def initialize(query)
    self.query = query
  end

  def results=(value)
    @results = (value.is_a?(Array) && value.count == 1) ? value.first : value
  end

  def perform
    if query =~ Ticket::REFERENCE_REGEXP
      self.results = Ticket.find_by_reference(query)
    else
      self.results = Ticket.search(query)
    end
    self.results
  end

  def single_result?
    self.results.is_a? Ticket
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

  STATUS = {
    :waiting_for_staff_response   => 0,
    :waiting_for_customer         => 1,
    :on_hold                      => 2,
    :cancelled                    => 3,
    :completed                    => 4
  }

  REFERENCE_REGEXP = /\A[A-Z]{3}-[0-9]{6}\z/

  attr_accessible :client_name, :client_email, :department_id, :subject, :body, :status

  belongs_to :department
  belongs_to :assignee, class_name: 'Member'
  has_many   :replies

  validates :client_name,  presence: true
  validates :client_email, presence: true, format: /@/
  validates :subject,      presence: true
  validates :body,         presence: true

  scope :unassigned, -> { where(assignee_id: nil).order('created_at DESC') }
  scope :open,       -> { where("status_id NOT IN (?)", [ STATUS[:cancelled], STATUS[:completed] ]) }
  scope :onhold,     -> { where(status_id: STATUS[:on_hold]) }
  scope :closed,     -> { where(status_id: [ STATUS[:cancelled], STATUS[:completed] ]) }

  define_index do 
    indexes subject, body
  end

  before_create :generate_reference
  after_commit  :send_notification,  on: :create
  before_save   :set_default_status

  def to_param
    self.reference
  end

  def status
    STATUS.invert[status_id]
  end

  def status=(value)
    self.status_id = STATUS[value]
  end

  def generate_reference
    self.reference = loop do
      random_reference = [*('A'..'Z')].sample(3).join + '-' + [*('0'..'9')].sample(6).join
      break random_reference unless Ticket.exists?(reference: random_reference)
    end
  end

  def set_default_status
    self.status = :waiting_for_staff_response unless self.status_id_changed?
  end

  def send_notification
    TicketNotifications.posted(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

end

app/controllers/staff/base_controller.rb
class Staff::BaseController < ActionController::Base

  protect_from_forgery
  layout 'staff'
  before_filter :authenticate_member!

end

app/controllers/staff/replies_controller.rb
class Staff::RepliesController < Staff::BaseController

  before_filter :load_ticket
  respond_to    :html

  def create
    @reply = Reply.new(params[:reply])
    @reply.ticket = @ticket
    @reply.author = current_member
    flash[:notice] = t('replies.created') if @reply.save

    respond_with [:staff, @ticket]
  end

  def load_ticket
    @ticket ||= Ticket.find_by_reference(params[:ticket_id])
  end

end

app/controllers/staff/tickets_controller.rb
class Staff::TicketsController < Staff::BaseController

  before_filter :load_ticket
  respond_to    :html

  %w/unassigned open onhold closed/.each do |action|
    define_method action do
      @filter  = action
      @tickets = Ticket.send(@filter)

      respond_with @tickets do |format|
        format.html { render 'list' }
      end
    end
  end

  def take_ownership
    @ticket.assignee = current_member
    flash[:notice] = t('tickets.took_ownership', reference: @ticket.reference) if @ticket.save
    
    respond_with @ticket do |format|
      format.html { redirect_to :back }
    end
  end

  def search
    @filter  = :search
    @search  = Search.new(params[:search][:query])
    @tickets = @search.perform

    redirect_to [:staff, @tickets] and return if @search.single_result?

    respond_with @tickets do |format|
      format.html { render 'list' }
    end
  end

  def load_ticket
    @ticket ||= Ticket.find_by_reference(params[:id])
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  before_filter :load_ticket
  respond_to    :html

  def create
    @ticket = Ticket.new(params[:ticket])
    respond_with @ticket do |format|
      if @ticket.save
        format.html { render }
      else
        format.html { render :new }
      end
    end
  end

  def new
    @ticket = Ticket.new
    respond_with @ticket
  end

  def update
    flash[:notice] = t('tickets.updated') if @ticket.update_attributes(params[:ticket])  

    respond_with(@product, :location => [@ticket])   
  end

  def load_ticket
    @ticket ||= Ticket.find_by_reference(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staff/replies_helper.rb
module Staff::RepliesHelper
  def format_reply(reply)
    result =  "%s: %s" % [reply.author, reply.response]
    result << " * Reassigned to #{reply.new_assignee}"     if reply.new_assignee.present?
    result << " * Status changed to #{t reply.new_status}" if reply.new_status.present?
    result
  end
end

app/helpers/staff/tickets_helper.rb
module Staff::TicketsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/_search_form.haml
= simple_form_for :search, url: search_staff_tickets_path do |f|
  = f.input :query
  = f.submit 'search'

app/views/layouts/application.haml
!!!
%html
  %head
    %title Suppert
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    - if content_for?(:caption)
      %h2= yield :caption
    = render 'shared/flashes'
    = yield

app/views/layouts/mail.haml
!!!
%html
  %body
    = yield

app/views/layouts/staff.haml
!!!
%html
  %head
    %title Suppert
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    %nav.top-bar
      %ul
        %li=link_to 'New unassigned tickets', unassigned_staff_tickets_path
        %li=link_to 'Open tickets', open_staff_tickets_path
        %li=link_to 'On hold tickets', onhold_staff_tickets_path
        %li=link_to 'Closed tickets', closed_staff_tickets_path
        - if member_signed_in?
          %li= link_to 'Log out', destroy_member_session_path, :method => :delete
    = render 'layouts/search_form'
    - if content_for?(:caption)
      %h2= yield :caption
    = render 'shared/flashes'
    = yield

app/views/shared/_flashes.haml
- if flash[:error]
  .error= flash[:error]
- if flash[:notice]
  .notice= flash[:notice]

app/views/shared/_replies.haml
- if replies.any?
  %ul
    - replies.each do |reply|
      %li=raw format_reply(reply)

- else
  %p No data available.

app/views/staff/replies/_form.haml
= simple_form_for [:staff, ticket, Reply.new] do |f|
  = f.input :response,          as: :text
  = f.input :new_assignee_id,   collection: Member.all.map {|d| [d.username, d.id]}
  = f.input :new_status_id,        collection: Ticket::STATUS.map {|s,i| [t(s), i]}
  = f.submit

app/views/staff/tickets/list.haml
- content_for :caption do
  = t "#{@filter}_tickets"

- if @tickets.any?
  %table
    %tr
      %th Reference
      %th Subject
      %th Assignee
      %th Status
      %th Actions
    - @tickets.each do |ticket|
      %tr
        %td=  link_to ticket.reference, [:staff, ticket]
        %td=  ticket.subject
        %td=  ticket.assignee
        %td=t ticket.status
        %td=  link_to 'Take ownership', [:take_ownership, :staff, ticket], method: 'put'
- else
  %p No data available.

app/views/staff/tickets/show.haml
- content_for :caption do
  Ticket #{ @ticket.reference }

%table
  %tr
    %td Client Name
    %td= @ticket.client_name
  %tr
    %td Client Email
    %td= @ticket.client_email
  %tr
    %td Department
    %td= @ticket.department
  %tr
    %td Subject
    %td= @ticket.subject
  %tr
    %td Message
    %td= @ticket.body
  %tr
    %td Assignee
    %td= @ticket.assignee
  %tr
    %td Status
    %td=t @ticket.status

%h3 Reply
= render partial: 'staff/replies/form', locals: {ticket: @ticket}

%h3 Replies
= render partial: 'shared/replies', locals: {replies: @ticket.replies}

app/views/ticket_notifications/posted.html.haml
Hello #{@ticket.client_name},
Your request has been received. #{link_to 'Check status', ticket_url(@ticket)}

app/views/ticket_notifications/replied.html.haml
Hello #{@ticket.client_name},
#{@reply.author} replied to your ticket #{ link_to @ticket.reference, ticket_url(@ticket) }: #{@reply.response}

app/views/tickets/_form.haml
= simple_form_for ticket do |f|
  = f.input  :client_name
  = f.input  :client_email, as: :email
  = f.input  :department_id, collection: Department.all.map {|d| [d.name, d.id]}, include_blank: false
  = f.input  :subject
  = f.input  :body,         as: :text
  = f.button :submit

app/views/tickets/create.haml
%p Your request has been received. #{ link_to 'Check status.', [@ticket] }

app/views/tickets/new.haml
- content_for :caption do
  Post your ticket
  
= render partial: 'form', locals: {ticket: @ticket}

app/views/tickets/show.haml
- content_for :caption do
  Ticket #{@ticket.reference}

= render partial: 'form',  locals: {ticket: @ticket}
%h3 Replies
= render partial: 'shared/replies', locals: {replies: @ticket.replies}